env:
  global:
    - secure: oFsC77WVP3ggPSSvW9ViS5gtperGGHtIs38MsBw79kIbIj3miamLVz8aR1gmSnHZu1oMf6LWG2N9O9WYYCJUGGn/G3C+SJ6MORVYLjm4cYspZBCaDrkHPcW37y8cBiDM1Ueyc7qOj25XMjwO2fTO2ujXPavOOlQCJSTbPtimrNg=
before_install:
  - sudo add-apt-repository --yes ppa:hansjorg/rust
  - sudo add-apt-repository --yes ppa:cmrx64/cargo
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq rust-nightly cargo
  - rustc -v
script:
  - cargo build
  - make doc
  - make test
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
