env:
  global:
    - secure: oFsC77WVP3ggPSSvW9ViS5gtperGGHtIs38MsBw79kIbIj3miamLVz8aR1gmSnHZu1oMf6LWG2N9O9WYYCJUGGn/G3C+SJ6MORVYLjm4cYspZBCaDrkHPcW37y8cBiDM1Ueyc7qOj25XMjwO2fTO2ujXPavOOlQCJSTbPtimrNg=
install:
  - wget http://www.rust-lang.org/rustup.sh
  - sudo sh ./rustup.sh
  - export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
  - rustc -v
script:
  - cargo build
  - make test
  - make doc
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
