env:
  global:
    - secure: oFsC77WVP3ggPSSvW9ViS5gtperGGHtIs38MsBw79kIbIj3miamLVz8aR1gmSnHZu1oMf6LWG2N9O9WYYCJUGGn/G3C+SJ6MORVYLjm4cYspZBCaDrkHPcW37y8cBiDM1Ueyc7qOj25XMjwO2fTO2ujXPavOOlQCJSTbPtimrNg=
install:
  - curl http://static.rust-lang.org/cargo-dist/cargo-nightly-linux.tar.gz |
    sudo tar --strip-components 1 -C /usr -xzf -
  - curl http://www.rust-lang.org/rustup.sh | sudo sh -
  - rustc -v
script:
  - cargo build
  - make doc
  - make test
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
